### ISSUE TITLE
post/patch body params?

### ISSUE THREAD

**Issue by ivanakimov** [hapijs/good-console#105]
Original post here: https://github.com/hapijs/good-squeeze/issues/27

I can't seem to get `POST` or `PATCH` body params to log (`GET` requests work fine tho). Am I doing something wrong? Or maybe it's a security issue to log request body?

Configs:
```javascript
...
console: [{
  module: 'good-squeeze',
  name: 'Squeeze',
  args: [{
    error: '*',
    response: '*',
    request: '*'
  }]
}
...
```

Output (with no body params):
```bash
Tuesday, April 24th 2018, 7:28:18 pm, (random) [response] http://localhost:8080: patch /test {} 200 (14ms)
```

**Comment by hueniverse** [comment]
No body data is logged. GET doesn't have a body hence...
