### ISSUE TITLE
Good options logRequestHeaders and logRequestPayload not logged to console

### ISSUE THREAD

**Issue by shaunbruno** [hapijs/good-console#36]
**Expected**
When logRequestHeaders and logRequestPayload are set to true, it's expected that good-console will log the headers and payload directly to console.

**Actual**
good-console does not log either request header or post payload

**Example Options**
```
var options = {
    opsInterval: 1000,
    reporters: [{
      reporter: require('good-console'),
      args:[{ log: '*', request: '*', response: '*' }]
    }],
    logRequestHeaders: true,
    logRequestPayload: true,
    logResponsePayload: true
  }
```

**Comment by AdriVanHoudt** [comment]
@arb will this be included in a minor of v5?

**Comment by arb** [comment]
Yep. As soon as someone gets to it.

**Comment by AdriVanHoudt** [comment]
I see :) if you see me on gitter chatting a lot tell me to do this instead ;)

**Comment by arb** [comment]
Logging this information to the console doesn't make sense. Use file logging. I will reconsider if more people want this feature.

**Comment by nackjicholson** [comment]
I would like request and response payload, because I'm using rsyslog to scoop up all console output and send it to an elasticsearch database. I'd really rather not do any log files.

**Comment by walling** [comment]
Logging all headers might be a bit too much, but I think it could be nice if it is possible to log select headers, fx. `X-Request-ID` that helps in tracking/debugging a request between multiple systems.

**Comment by shinzui** [comment]
@arb The [best practice](http://12factor.net/logs) is to stream all logs to stdout, especially if you are running your service in Docker. This is a blocking issue for us, logging from our microservices will become much more complicated without this.

**Comment by arb** [comment]
@shinzui if you upgrade to good version 7, it would be trivial to pipe everything to stdout. Rather than using good-console, you'd write your own simple tranform stream, or just use good-squeeze to stringify everything and pipe that to std out.

Good console isn't going to change to add this feature, but you can easily get what you're after with other and already existing tools.
