### ISSUE TITLE
missing init method "Error: Every reporter object must have an init method"

### ISSUE THREAD

**Issue by Black-Star** [hapijs/good-console#39]
Below are my server settings and when i start server 
I am getting Error: Every reporter object must have an init method

Error: Every reporter object must have an init method

    var Good = require('good');
    server.register({
        register: Good,
        options: {
            reporters: [{
                reporter: require('good-console'),
                events:{ log: '*', response: '*' }
            }]
        } }, function (err) {
        if (err) {
            throw err; // something bad happened loading the plugin
        }
        server.start(function () {
            server.log('info', 'Server running at: ' + server.info.uri);
        }); });

**Comment by lloydbenson** [comment]
what versions of good and good-console are you using?  I suspect not the latest and you have a mismatch.

**Comment by Black-Star** [comment]
Thanks ..solved the problem

**Comment by lloydbenson** [comment]
Great glad that is all it was.
