### ISSUE TITLE
No newlines after upgrade

### ISSUE THREAD

**Issue by leobudima** [hapijs/good-console#71]
After upgrading to good@7.0.0-rc1 and good-console@6.0.0, using the configuration from the npm page example, I'm currently getting all the output without newlines in terminal (Mac OS X). Is there a configuration option that I'm missing, perhaps?  Thanks

**Comment by arb** [comment]
No that was something that got missed in the update. I'll accept a PR adding new lines.

**Comment by arb** [comment]
Closed via 3e1fdbbe831c2dfc8c166a8154a8539445808577
