### ISSUE TITLE
Unable to turn off ops logs

### ISSUE THREAD

**Issue by twler** [hapijs/good-console#79]
I'm trying to configure `good-console` to show only http request / response, and there doesn't appear to be any way to turn off the ops messages:

    161120/052304.141, [ops] memory: 67Mb, uptime (seconds): 15.871, load: [1.57563259375,1.7333911375,1.69970603125]

Is there a way to do this?  I have tried all kinds of configurations, e.g.

```
    register: require('good'),
    options: {
      reporters: {
        goodConsoleReporter: [{
          module: 'good-console',
          args: [{ request: '*', response: '*', ops: false, log: false, error: false }]
        }, 'stdout']
      }
    }
```

**Comment by Marsup** [comment]
That's in the docs https://github.com/hapijs/good/blob/master/API.md#options.
