### ISSUE TITLE
Wrong version number

### ISSUE THREAD

**Issue by antonsamper** [hapijs/good-console#81]
hi @arb ,

i think the last release was published with the wrong version number. I was using `v6.3.1` but on the releases page and on `npm outdated` it says the latest version is `v6.2.0`.

**Comment by antonsamper** [comment]
<img width="922" alt="screen shot 2016-12-09 at 17 46 44" src="https://cloud.githubusercontent.com/assets/102233/21058829/c5145fde-be37-11e6-8910-d3055ad5961a.png">

**Comment by arb** [comment]
Updating GH releases really isn't part of the normal hapi module release cycle. As long as the tags and npm are up-to-date, that is what is most important. I'll tag the latest release, but in the future, this doesn't require an issue. 

`npm outdated` looks at what you have installed compared to what's on npm. The things listed under GitHub releases have no bearing on that as is really just a nice way to view tagged SHAs.

**Comment by arb** [comment]
Ok so here is what I did...

- deprecated 6.3.1 as that was supposed to be 6.1.3 and left a message
- published what was supposed to be 6.1.3 to npm and added a git tag to the repo
- updated the "latest" tag on good-console to point to 6.2.0

Thanks for calling this out!

**Comment by kanongil** [comment]
You really should re-release 6.2.0 as 6.3.2 or something.
