### ISSUE TITLE
request.log tagged as error

### ISSUE THREAD

**Issue by travi** [hapijs/good-console#84]
is there a way to have Error object logged to `request.log` with a tag of `error` printed in the same way as an `error` event type? the current formatting hides most of the valuable information from the console output.

**Comment by arb** [comment]
This sounds like a great use case for your own transform stream.

**Comment by travi** [comment]
thats what i kind of expected the answer to be, but thought it might be a common enough use case for good-console to handle it that way.

fair enough. thanks for the quick response
