### ISSUE TITLE
I just want to print the good console logs with time, please find the below code which i am using 

### ISSUE THREAD

**Issue by rpasunuri** [hapijs/good-console#87]
var goodOptions = {
    opsInterval: 1000
    ,
    reporters :[
    {
        reporter: require('good-console'),
        args:[{ log: '*', request: '*' }]
    }
    ,{
        reporter : require('good-file'),
        args : ['hapilog.log',{ opts : '*'  , request : '*' , log : '*'}]
    }
    ]
};
server.pack.register([
    {
        plugin: require("good"),
        options: goodOptions
    },
    {
        plugin : require('../plugins/hapijwt')
    }
], function(err) {
    if (err) throw err;
});

Output:
server-0 (out): 170224/105245.779, request, https://0.0.0.0:8091: options /v1/logout {} 200 (40ms)
server-0 (out): 170224/105245.827, request, https://0.0.0.0:8091: post /v1/logout {} 200 (241ms)

**Comment by AdriVanHoudt** [comment]
what output do you want? can you give an example?

**Comment by thebergamo** [comment]
@rpasunuri The time are already printed in the log. The current format is: `YYMMDD/HHmmss.SSS`

In the config object passed in the constructor of the `new GoodConsole(config)` you can specify another date format. GoodConsole support the syntax of [MomentJS](http://momentjs.com/docs/#/displaying/format/)

As an example of how to use: 
```javascript
  const Good = require('good');

  const goodOpts = {
    opsInterval: 1000,
    reporters: [{
      reporter: require('good-console'),
      args: [{ format: 'YYYY-MM-DD hh:mm:ss' }],
      events: {error: '*', log: '*', response: '*', request: '*'}
    }]
  };

  server.register({
    register: Good,
    options: goodOpts
  });
```
