### ISSUE TITLE
Ignore log of specific routes

### ISSUE THREAD

**Issue by juanprietob** [hapijs/good-console#88]
Is it possible to configure good-console to ignore events in a specific route?

**Comment by juanprietob** [comment]
Great thanks for the tip. 
If I understand correctly, I need to implement a new transform as in: 
https://github.com/hapijs/good-squeeze/blob/master/lib/safe-json.js ?

**Comment by arb** [comment]
Yep that's the general idea. If you don't want it reported to good-console, don't call call `next` with no data.

As far as filtering goes, you can set route level options as well for additional filtering options. See https://github.com/hapijs/good/blob/master/API.md#stream-transforms-using-plugin-configs for an example.

**Comment by juanprietob** [comment]
Thanks!
I have posted an example of my solution here https://stackoverflow.com/questions/32830012/how-to-make-hapi-good-ignore-a-specific-route/42840562#42840562
