### ISSUE TITLE
How should I use the [config] - optional configuration object?

### ISSUE THREAD

**Issue by cteevin** [hapijs/good-console#89]
Hello guys, I have the following code:

    'use strict';
    import routes from './server/routes';
    import conf from '../config.js';
    import Hapi from 'hapi';
    import Good from 'good';
    import Util from './server/lib/util';

    const connectivity = {
      host: conf.APP.host,
      address: conf.APP.address,
      port: conf.APP.port
    };

    const goodOptions = {
      register: Good,
      options: {
        ops: {
          interval: Util.rightTime(conf.LOG.console.intervalType, conf.LOG.console.intervalTime)
        },
        reporters: {
          consoleReporter: [{ module: 'good-console' }, 'stdout']
        }
      }
    };

    const server = new Hapi.Server();
    server.debug = false;
    server.connection(connectivity);
    server.register([
      goodOptions
    ], function(err) {
      if (err) {
        return console.error(err);
      }
      server.log('info', `Admin API - Server Starting...`);
      server.route(routes);
      server.log('info', `Admin API - Server Routes loaded...`);
      server.start(function(err) {
        if (err) {
          server.log('error', 'Admin API - Failed to start server');
          server.log('error', err);
          throw err;
        }
        server.log('info', `Admin API - Server started at ${ server.info.uri }`);
      });
    });

My app is working perfectly but for the console log from Good, it is like this:

![image](https://cloud.githubusercontent.com/assets/6021572/24889243/84d4c2ea-1e2e-11e7-87e0-e280c88bf1af.png)

I want to show that log in a different datetime format, for example:
YYYY-MM-DD HH:mm:ss, and I want to use my local server time, and not UTC

I've found this in your README
_Creates a new GoodConsole object with the following arguments:_
_[config] - optional configuration object with the following keys
  format - MomentJS format string. Defaults to 'YYMMDD/HHmmss.SSS'.
  utc - boolean controlling Moment using utc mode or not. Defaults to true.
  color - a boolean specifying whether to output in color. Defaults to true._

And prepared this

      config: {
        format: 'YYYYMMDD/HHmmss.SSS',
        utc: false,
        color: true
      }

But it doesn't matter where I set this code, the log keeps showing the info with the default configuration.
**Could you please tell me where should I set the config json considering the code I am posting here?**

**Cheers.**

**Comment by arb** [comment]
https://github.com/hapijs/good/blob/master/API.md#options

You need the `args` option. That is how you pass arguments to the stream constructor.

```js
consoleReporter: [{
  module: 'good-console',
  args: [{
    format: 'YYYYMMDD/HHmmss.SSS',
    utc: false,
    color: true
  }]
}, 'stdout']
```

**Comment by cteevin** [comment]
Working perfectly. Thanks Adam!
