### ISSUE TITLE
wreck events are not formatted correctly in console logging

### ISSUE THREAD

**Issue by adityabakle** [hapijs/good-console#90]
using the below config i see other logs but wreck event is logged twice and no data. 
"good": "7.x.x",
"good-console": "6.x.x",
"good-squeeze": "5.x.x",
"hapi": "16.x.x",
"wreck": "10.x.x"

```javascript
goodOpts: {
        wreck: true,
        reporters: {
            console: [{
                module: 'good-squeeze',
                name: 'Squeeze',
                args: [{ request: '*', error: '*', response: '*', wreck: '*', log: '*' }]
            }, {
                module: 'good-console'
            }, 'stdout']
        }
    }
```

Output
```
170524/132408.679, [wreck] data: (none)
170524/132408.679, [wreck] data: (none)
170524/132408.944, [wreck] data: (none)
170524/132408.945, [wreck] data: (none)
```
These are two wreck events each logged twice. 
I saw that there is no formatting for wreck event in good-console hence data is printed as (none).. is that correct ?

**Comment by arb** [comment]
I'm not sure why there are two logs for each wreck event. The wreck logging picks up wreck requests that happen *anywhere* in the application. So if you're using anything that makes wreck requests, they'll show up.

As far as the output goes... good-console wasn't really designed with wreck in mind. Looking at the code I don't think it would be too hard to add in. You could also write your own transform stream just for wreck logging and pipe it to stdout as well.
