### ISSUE TITLE
Example good integration for transforming events into strings

### ISSUE THREAD

**Issue by lostthetrail** [hapijs/good-console#91]
@arb Any chance you have an example of a simple Good integration that takes any event and converts it to a string.

Here in the good-console plugin, you do two function:
1. convert events to strings
2. write to stdout

I want to have a event stringifier that I could pipe to either good-file or stdout, both with the same results.. any thoughts there?

Sorry this is a bit rambling, trying to form the idea...

**Comment by lostthetrail** [comment]
If you don't have an example, I might toss one together.. the general idea is to write the logs we currently do via good-console but to disk. So we would need to move the formatting out into something before good-file.

**Comment by arb** [comment]
Couldn't you just use good-console and pipe that into good-file?

**Comment by lostthetrail** [comment]
Hah, you are totally right. good-console could easily be renamed "good-transform-events-to-strings". Amazing what some sleep will do for my ability to think straight.
Thanks @arb!
